f1105:PhoneNumber.o fig11_05.o
	g++ -o f1105  PhoneNumber.o fig11_05.o
PhoneNumber.o:PhoneNumber.h
	g++ -c PhoneNumber.cpp
fig11_05.o:fig11_05.cpp
	g++ -c fig11_05.cpp
clean:
	rm f1105 PhoneNumber.o fig11_05.o
